---
title: "actividades frecuente"
output: html_document
---

```{r}
library(rgdal)
library(leaflet)
library(readxl)
library(ggplot2)
library(modeest)
library(fmsb)
library(dplyr)
library(cluster)
library(factoextra)
library(rgdal)
library(leaflet)
library(tidyverse)
library(sf)
```

```{r}
encuesta_calidad_vida <- read_delim("C:/Users/yosma/OneDrive/Desktop/analisis/encuesta_calidad_vida.csv", 
                                    ";", escape_double = FALSE, trim_ws = TRUE)
view(encuesta_calidad_vida)
names (encuesta_calidad_vida)[9] = "encuesta_calidad.fecha"
```

```{r}
fecuencia_Activ <- encuesta_calidad_vida [,c("encuesta_calidad.barrio","encuesta_calidad.p_7",
                                       "encuesta_calidad.fecha","encuesta_calidad.p_15"
                                       
                                       ,"encuesta_calidad.p_133"
                                       ,"encuesta_calidad.p_135"
                                       )]
fecuencia_Activ <- filter(fecuencia_Activ, encuesta_calidad.fecha == "2018")
names(fecuencia_Activ) <- c("barrio","barrio_numerica","fecha","sexo"
                      ,"Frecuencia_recreativas"
                      ,"Frecuencia_deportivas")

```


```{r}
fecuencia_Activ$Frecuencia_recreativas[(fecuencia_Activ$Frecuencia_recreativas==-88) ]<-NA

fecuencia_Activ$Frecuencia_deportivas[(fecuencia_Activ$Frecuencia_deportivas==-88) ]<-NA
```

```{r}
summary(fecuencia_Activ)
```

```{r}
fecuencia_Activ <- fecuencia_Activ[!is.na(fecuencia_Activ$Frecuencia_deportivas),]
fecuencia_Activ <- fecuencia_Activ[!is.na(fecuencia_Activ$Frecuencia_recreativas),]
```

```{r}
summary(fecuencia_Activ)
```

```{r}
frecu_activ <- fecuencia_Activ %>% 
  group_by(barrio,Frecuencia_deportivas,Frecuencia_recreativas) %>%
  summarise(num_pers = n())

frecu_activ1 <-frecu_activ

frecu_activ1 <- frecu_activ1[,c(-1)]

rownames(frecu_activ1) = paste0(frecu_activ$barrio, 1:nrow(frecu_activ))

```


```{r}
ggplot(frecu_activ1, aes(Frecuencia_deportivas, num_pers
                   , fill=Frecuencia_deportivas)) +
  geom_bar(stat = "identity") +
  labs(title = "Frecuencia cuantas persona hace ejercicio",
       x = "Hace ejercicio",
       y = "Número de estudio") +
  scale_fill_gradient(low = "#65B1F7", high = "#132B43") +
  scale_y_continuous(breaks = seq(0, 1200, 150))
```

```{r}
ggplot(frecu_activ1, aes(Frecuencia_recreativas, num_pers
                   , fill=Frecuencia_recreativas)) +
  geom_bar(stat = "identity") +
  labs(title = "Frecuencia cuantas persona hace ejercicio",
       x = "Hace ejercicio",
       y = "Número de estudio") +
  scale_fill_gradient(low = "#65B1F7", high = "#132B43") +
  scale_y_continuous(breaks = seq(0, 1200, 200))
```

```{r}
frecu_activ2 <- frecu_activ1 %>% 
  filter( califica_estado_de_salud == 4) %>%
  group_by(Excelente = califica_estado_de_salud) %>% 
  summarise(num_per = n())
salud_2 <- salud %>% 
  filter( califica_medico_especialista == 4) %>%
  group_by(Excelente = califica_medico_especialista) %>% 
  summarise(num_per = n())
salud_3 <- salud %>% 
  filter( califica_medico_general == 4) %>%
  group_by(Excelente = califica_medico_general) %>% 
  summarise(num_per = n())

salud_1$Excelente<- gsub("4","estado de salud",salud_1$Excelente)
salud_2$Excelente<- gsub("4","calificacion medico",salud_2$Excelente)
salud_3$Excelente<- gsub("4","cali medico Espe",salud_3$Excelente)

salud_1 <- rbind(salud_1, salud_2)
salud_1 <- rbind(salud_1, salud_3)


ggplot(salud_1, aes(Excelente, num_per, fill = num_per)) +
  geom_bar(stat = "identity") +
  labs(title = "Frecuencia de ultimo estudio aprobado",
       x = "estudio",
       y = "Número de estudio") +
  scale_fill_gradient(low = "#65B1F7", high = "red") +
  scale_y_continuous(breaks = seq(0, 1000, 50))
```




```{r}
R <-frecu_activ1


R<- scale(R)

set.seed(1234)
wss<-(nrow(R)-1)*sum(apply(R,2,var))
for(i in 1:20) wss[i]<-sum(kmeans(R,centers = i)$withinss)
```


```{r}
ggplot() + geom_point(aes(x = 1:20, y = wss), color = 'blue') + 
  geom_line(aes(x = 1:20, y = wss), color = 'blue') + 
  ggtitle("Método del Codo") + 
  xlab('Cantidad de Centroides k') + 
  ylab('WSS')
```

```{r}
mycluster <- kmeans(R, 4, nstart = 5, iter.max = 3000)
mycluster
```


```{r}
fviz_cluster(object = mycluster, data = R, show.clust.cent = TRUE,
             ellipse.type = "euclid", star.plot = TRUE, repel = TRUE) +
  labs(title = "Resultados clustering K-means") +
  theme_bw() +
  theme(legend.position = "none")
```